# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/


[de]
  languageCode = "de"
  contentDir = "content/de"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[en]
  languageCode = "en"
  contentDir = "content/en"
  title = "Friedli Engineering & Production"
  [en.params]
    description = "XXX"
[[en.menu.main]]
  name = "Start"
  url = "#action"
  weight = 1
[[en.menu.main]]
  name = "We are"
  url = "#wir"
  weight = 20
[[en.menu.main]]
  name = "References"
  url = "#referenzen"
  weight = 40
[[en.menu.main]]
  name = "Technology"
  url = "#technologien"
  weight = 50
[[en.menu.main]]
  name = "Jobs"
  url = "#jobs"
  weight = 60
  [[en.menu.main]]
  name = "Contact"
  url = "#kontakt"
  weight = 60
